language: node_js
node_js:
- '6'
branches:
  only:
  - master
  - develop
notifications:
  email:
    on_failure: always
install: true
deploy:
  provider: npm
  email: npm@lukechavers.com
  on:
    repo: vmadman/cli
